openapi: 3.0.3
info:
  title: Music Band Management API
  description: |
    Main API for managing a collection of music bands.
    
    This service provides complete CRUD operations for music bands with advanced filtering, 
    sorting, pagination, and statistical operations.
  version: 1.0.0
  contact:
    name: API Support
    email: support@musicband.api
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://helios:8080/api/v1
    description: Production Main API server on Helios

tags:
  - name: MusicBand
    description: Operations with music bands
  - name: Statistics
    description: Statistical operations

paths:
  /bands:
    get:
      tags:
        - MusicBand
      summary: Get list of music bands
      description: |
        Getting an array of music bands with support for:
        - Filtering by any fields
        - Sorting by any combination of fields
        - Paginated output of results
      operationId: getBands
      parameters:
        - name: page
          in: query
          description: Page number (starts from 0)
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
          example: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
          example: 20
        - name: sort
          in: query
          description: Fields for sorting
          required: false
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
          example: ["name,asc", "numberOfParticipants,desc"]
        - name: filter
          in: query
          description: |
            Advanced filtering with operators. Format: field:operator:value
            
            Supported operators:
            - eq (equals)
            - ne (not equals) 
            - gt (greater than)
            - gte (greater than or equal)
            - lt (less than)
            - lte (less than or equal)
            - contains (contains substring)
            
            Examples:
            - name:contains:Beatles (name contains "Beatles")
            - numberOfParticipants:gt:3 (more than 3 participants)
            - albumsCount:gte:10 (10 or more albums)
            - genre:eq:POP (genre equals POP)
          required: false
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
          examples:
            nameContains:
              summary: Name contains substring
              value: ["name:contains:Beatles"]
            participantsGreater:
              summary: More than 3 participants
              value: ["numberOfParticipants:gt:3"]
            multipleFilters:
              summary: Multiple filters
              value: ["genre:eq:POP", "albumsCount:gte:5", "numberOfParticipants:lte:6"]
      responses:
        '200':
          description: List of music bands
          content:
            application/xml:
              schema:
                type: object
                properties:
                  bands:
                    type: array
                    items:
                      $ref: '#/components/schemas/MusicBand'
                  totalElements:
                    type: integer
                    format: int64
                    description: Total number of elements
                  totalPages:
                    type: integer
                    format: int32
                    description: Total number of pages
                  currentPage:
                    type: integer
                    format: int32
                    description: Current page
                  pageSize:
                    type: integer
                    format: int32
                    description: Page size
                xml:
                  name: bandsResponse
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - MusicBand
      summary: Create new music band
      description: Adding a new band to the collection
      operationId: createBand
      requestBody:
        description: New band data
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/MusicBand'
            example: |
              <?xml version="1.0" encoding="UTF-8"?>
              <musicBand>
                <name>The Beatles</name>
                <coordinates>
                  <x>10.5</x>
                  <y>100</y>
                </coordinates>
                <numberOfParticipants>4</numberOfParticipants>
                <albumsCount>13</albumsCount>
                <genre>POP</genre>
                <label>
                  <sales>1000000.50</sales>
                </label>
              </musicBand>
      responses:
        '201':
          description: Band successfully created
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBand'
        '400':
          $ref: '#/components/responses/BadRequestBody'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /bands/{id}:
    get:
      tags:
        - MusicBand
      summary: Get music band by ID
      description: Getting information about a specific music band
      operationId: getBandById
      parameters:
        - name: id
          in: path
          description: Band ID
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
          example: 1
      responses:
        '200':
          description: Music band information
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBand'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - MusicBand
      summary: Update music band
      description: Updating music band information
      operationId: updateBand
      parameters:
        - name: id
          in: path
          description: Band ID
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
          example: 1
      requestBody:
        description: Updated music band data
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/MusicBand'
      responses:
        '200':
          description: Band successfully updated
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBand'
        '400':
          $ref: '#/components/responses/BadRequestBody'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

    patch:
      tags:
        - MusicBand
      summary: Partially update music band
      description: |
        Partial update of music band information. Only provided fields will be updated.
        Unlike PUT, PATCH allows updating individual fields without affecting others.
      operationId: patchBand
      parameters:
        - name: id
          in: path
          description: Band ID
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
          example: 1
      requestBody:
        description: |
          Partial music band data for update. Only include fields you want to modify.
          All validation rules still apply to provided fields.
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  description: Music band name (cannot be null or empty)
                  example: "The Beatles"
                coordinates:
                  $ref: '#/components/schemas/Coordinates'
                numberOfParticipants:
                  type: integer
                  format: int32
                  minimum: 1
                  description: Number of band participants (must be greater than 0)
                  example: 4
                albumsCount:
                  type: integer
                  format: int32
                  minimum: 1
                  nullable: true
                  description: Number of albums (can be null, if specified - must be greater than 0)
                  example: 13
                genre:
                  $ref: '#/components/schemas/MusicGenre'
                label:
                  $ref: '#/components/schemas/Label'
              xml:
                name: musicBandPatch
            example: |
              <?xml version="1.0" encoding="UTF-8"?>
              <musicBandPatch>
                <name>The Beatles Updated</name>
                <numberOfParticipants>5</numberOfParticipants>
              </musicBandPatch>
      responses:
        '200':
          description: Band successfully patched
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBand'
        '400':
          $ref: '#/components/responses/BadRequestBody'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - MusicBand
      summary: Delete music band
      description: Removing band from collection
      operationId: deleteBand
      parameters:
        - name: id
          in: path
          description: Band ID
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
          example: 1
      responses:
        '204':
          description: Band successfully deleted
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /bands/statistics/average-participants:
    get:
      tags:
        - Statistics
      summary: Get average number of participants
      description: Calculates the average value of numberOfParticipants field for all bands in the collection
      operationId: getAverageParticipants
      responses:
        '200':
          description: Average number of participants
          content:
            application/xml:
              schema:
                type: object
                properties:
                  averageParticipants:
                    type: number
                    format: double
                    description: Average number of participants
                    example: 4.2
                  totalBands:
                    type: integer
                    format: int32
                    description: Total number of bands in the sample
                    example: 50
                xml:
                  name: averageParticipantsResponse
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    MusicBand:
      type: object
      required:
        - name
        - coordinates
        - numberOfParticipants
        - genre
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          description: Unique band ID (generated automatically)
          readOnly: true
          example: 1
        name:
          type: string
          minLength: 1
          description: Music band name (cannot be null or empty)
          example: "The Beatles"
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date
          description: Record creation date (generated automatically)
          readOnly: true
          example: "2023-12-01"
        numberOfParticipants:
          type: integer
          format: int32
          minimum: 1
          description: Number of band participants (must be greater than 0)
          example: 4
        albumsCount:
          type: integer
          format: int32
          minimum: 1
          nullable: true
          description: Number of albums (can be null, if specified - must be greater than 0)
          example: 13
        genre:
          $ref: '#/components/schemas/MusicGenre'
        label:
          $ref: '#/components/schemas/Label'
      xml:
        name: musicBand

    Coordinates:
      type: object
      required:
        - y
      properties:
        x:
          type: number
          format: double
          description: X coordinate
          example: 10.5
        y:
          type: integer
          format: int64
          maximum: 945
          description: Y coordinate (maximum value 945, cannot be null)
          example: 100
      xml:
        name: coordinates

    Label:
      type: object
      properties:
        sales:
          type: number
          format: double
          minimum: 0
          exclusiveMinimum: true
          description: Label sales (value must be greater than 0)
          example: 1000000.50
      xml:
        name: label

    MusicGenre:
      type: string
      enum:
        - PROGRESSIVE_ROCK
        - POP
        - MATH_ROCK
      description: |
        Music genre. Order for comparison:
        - PROGRESSIVE_ROCK (0)
        - POP (1) 
        - MATH_ROCK (2)
      example: POP

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
          example: 400
        message:
          type: string
          description: Error message
          example: "Validation failed"
        details:
          type: string
          description: Detailed error description
          example: "Field 'name' cannot be empty"
        timestamp:
          type: string
          format: date-time
          description: Error occurrence time
          example: "2023-12-01T10:30:00Z"
      xml:
        name: error

  responses:
    BadRequestBody:
      description: Invalid request body or malformed XML
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Error'
          example: |
            <?xml version="1.0" encoding="UTF-8"?>
            <error>
              <code>400</code>
              <message>Invalid request body</message>
              <details>Malformed XML or missing required fields</details>
              <timestamp>2023-12-01T10:30:00Z</timestamp>
            </error>

    UnprocessableEntity:
      description: Business logic validation failed
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Error'
          example: |
            <?xml version="1.0" encoding="UTF-8"?>
            <error>
              <code>422</code>
              <message>Business validation failed</message>
              <details>Field 'name' cannot be empty or numberOfParticipants must be greater than 0</details>
              <timestamp>2023-12-01T10:30:00Z</timestamp>
            </error>
    
    NotFound:
      description: Resource not found
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Error'
          example: |
            <?xml version="1.0" encoding="UTF-8"?>
            <error>
              <code>404</code>
              <message>Resource not found</message>
              <details>MusicBand with id 123 not found</details>
              <timestamp>2023-12-01T10:30:00Z</timestamp>
            </error>
    
    InternalServerError:
      description: Internal server error
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Error'
          example: |
            <?xml version="1.0" encoding="UTF-8"?>
            <error>
              <code>500</code>
              <message>Internal server error</message>
              <details>An unexpected error occurred while processing the request</details>
              <timestamp>2023-12-01T10:30:00Z</timestamp>
            </error>

    ServiceUnavailable:
      description: Service unavailable error
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Error'
          example: |
            <?xml version="1.0" encoding="UTF-8"?>
            <error>
              <code>503</code>
              <message>Service unavailable error</message>
              <details>URI /bands/1 is not available</details>
              <timestamp>2023-12-01T10:30:00Z</timestamp>
            </error>

  parameters:
    BandId:
      name: id
      in: path
      description: Band ID
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
      example: 1

    PageParam:
      name: page
      in: query
      description: Page number (starts from 0)
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0

    SizeParam:
      name: size
      in: query
      description: Page size
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20